# Generated by Django 2.1.15 on 2022-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='posted',
        ),
        migrations.AddField(
            model_name='post',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='lastpost',
            field=models.URLField(default='https://test.com', max_length=1000, unique=True),
        ),
    ]
