# Generated by Django 2.1.15 on 2022-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0002_auto_20221111_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brandurl',
            field=models.URLField(default='https://test.com', max_length=1000, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='havenewpost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='totalpost',
            field=models.IntegerField(default=-1),
        ),
    ]
