# Generated by Django 2.1.15 on 2022-11-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0003_auto_20221112_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='havenewpost',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='lastpost',
            field=models.URLField(default='https://test.com', max_length=1000),
        ),
    ]
